name: Release

on:
  push:
    branches:
      - release


jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine
    
     # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      rtsp:
        # Docker Hub image
        image: aler9/rtsp-simple-server
        #
        ports:
          # Opens tcp port 6379 on the host and service container
          - 6379:6379    
          - 8554:8554
          - 1935:1935
          - 9997:9997
        env:
          RTSP_API: yes
        
          
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
#      - name: Build docker
#        run: | 
#          echo ---Building and starting up docker---
#          curl -v http://rtsp:9997/v1/paths/list
#          curl -v http://127.0.0.1:9997/v1/paths/list
#          curl -v http://127.0.0.1:1935/test
#          echo ---Containers up---        
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Publish JAR
        run: ./mvnw -B release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}